### ISSUE TITLE
Nearly perfect

### ISSUE THREAD

**Issue by Ancel1** [usineur/SDLPoP#3]
Hello, I wanted 1rst to give you a big thank for this prince of persia game on switch. On version 1.1 I could finish the game without any issues. The only thing that could be change (if possible) will be to be able to remove time during a game. It is possible to remove it but game need to be restard first. If you start without time removal you cannot change it later... But it was more to congrat you than anything else, well done!!!

**Comment by usineur** [comment]
Hi, indeed, it's not possible to remover timer when a game is started.
Btw, in the PC version of SDLPoP, it's possible to increase/decrease time left (minute per minute) using +/- keyboard buttons (when cheats are enabled).

I can offer you to map them to ZL/ZR on the switch port. Is that ok to you ?

**Comment by Ancel1** [comment]
Can be an good Idea, it mean enable cheat mode and then be able to change time from ZL/ZR key.

**Comment by usineur** [comment]
Done. It will be available in the next release.
