### ISSUE TITLE
Maybe include pop version 1.3?

### ISSUE THREAD

**Issue by rsn8887** [usineur/SDLPoP#4]
There were several version of MS-DOS POP and their data files all seem to be supported by SDLPOP, at least from my tests on Vita. MS-DOS POP version 1.3 data files are especially nice because they introduced more dungeon colors. For example, level 3 is green instead of blue in this version. See here for screenshots:
![](https://popuw.com/images/pop13.jpg)

Maybe one could bundle the v1.3 data files, or do you prefer the older version?

**Comment by usineur** [comment]
Well, I think I prefer the classic version.

Btw, thx for pointing this to me. I will add a comment in next releases to mention the existence of 1.3 data files.
