### ISSUE TITLE
Switch version for atmosphère 0.19.2

### ISSUE THREAD

**Issue by Ancel1** [usineur/SDLPoP#7]
Hello, would it be possible to get an update for newest atmosphère version on nitendo Switch ?
New librairies may be needed as for now it crash the device.

Atmosphère 0.19.2 not working

Many thanks

**Comment by usineur** [comment]
https://www.ferb.fr/switch/SDLPoP.nro

**Comment by Ancel1** [comment]
Thank you so much dude, it work perfectly!
How can I offer you a beer?

Le dim. 23 mai 2021 à 00:41, Matthieu Milan ***@***.***> a
écrit :

**Comment by usineur** [comment]
No problem.
Well if you want to: https://www.paypal.com/paypalme/usineur0
