### ISSUE TITLE
Not working on AMS 0.19.x and FW 12.0.x

### ISSUE THREAD

**Issue by StiraGHB** [usineur/SDLPoP#8]
Hello,

I was writing to inform you that the software is broken on AMS 0.19.x. Apparently this is a known issue with homebrew so I think it just needs to be recompiled.

styra

**Comment by usineur** [comment]
https://www.ferb.fr/switch/SDLPoP.nro

**Comment by StiraGHB** [comment]
Thank you! I do think this should be available on the releases tab so people don't get confused.
